### ISSUE TITLE
v2 checklist

### ISSUE THREAD

**Issue by frolic** [latticexyz/emojimon#9]
- [x] rebase to remove `useMapConfig` (changed approach)
- [x] remove `MapSystem` from the starter kit?
- [x] rename `Encounter.tsx` to `EncounterScreen.tsx` to not conflict with Encounter RECS component
- [x] fix encounter animation bug
- [x] update mud
- [x] use escaped double quotes in dev scripts for windows
